name: Generate Ascii Code

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4.2.2
            - name: List files
              run : ls -ltra
            - name: Excuting shell script
              run: ./ascii-sctipt.sh