name: workflow 1
on: push


jobs:
    ahmed:
        needs: ahmed2
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Welcome 
              run: |
                echo "Hello world"
            - name: cat dragon.txt
              run: cat dragon.txt
    ahmed2:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: script
              run: |
                ls -ltra
                chmod +x .github/workflows/script.sh 
                sh .github/workflows/script.sh
                

